{
        "title": "Commandr demo - simple CLI args",
        "version": "1.0",
        "schema_version": "1.0",
        "args": [
            {
                "name": "infile",
                "cli": "-i",
                "type": "str",
                "required": True
            },
            {
                "name": "count",
                "cli": "-c|--count",
                "type": "int",
                "default": 666,
                "env": "COMMANDR_COUNT"
            },
            {
                "name": "config",
                "cli": "--config",
                "default": "config/config.yaml",
                "loadconfig": True
            },
            {
                "name": "verbose",
                "cli": "-v|--verbose",
                "type": "switch",
                "env": "COMMANDR_VERBOSE" 
            }
        ]
    }