---
tasks:
  - name: "rosbag_topicshow"
    inputs:
      input: "/home/julius/dumps/ros1-cart-b_2023-07-04-13-52-45.bag" # franka + joint states
      msgpath:
    description: "Read ROS bag file and show all topics and their fields."

  - name: "field_extract"
    inputs:
      input: "/home/julius/dumps/ros1-cart-b_2023-07-04-13-52-45.bag" # franka + joint states
      output: "/home/julius/devel/ros-viz-helpers/target/ros1_extract.csv"
      topic: "/franka_states"
      timecol: "time"
      field: 
        - "q"
        - "dq"
        - "tau_J"
      msgpath:
    description: "Extract selected topics and fields from ROS bag file to CSV"